name: Dateshift MacOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate
      run: brew install make libtool automake autoconf && ./autogen.sh
    - name: Configure
      run: MAKE="gmake" ./configure --prefix=`pwd`/inst-prefix
    - name: Build
      run: mkdir -p `pwd`/inst-prefix/lib && gmake install
    - name: Test
      run: SRC=`pwd`; cd "$SRC/inst-prefix/bin" && "$SRC/run_tests.sh"
